### ISSUE TITLE
Read data from DHT22 using "rpi", a sub-project of hawa?

### ISSUE THREAD

**Issue by anhdenday** [PoJD/hawa#78]
Dear Dear PoJD, 
I try to run you code but only for "rpi" here: https://github.com/PoJD/hawa/tree/master/rpi
Because I just want to read data from DHT22 on my raspberry pi 2. I don't need to run whole your project! I do it as following.
1- Install pi4j on my device raspberry pi 2
2- Create a main method on the "Dht22Am2302TemperatureAndHumiditySensor.java" class like this: 

> public static void main(String[] args) {
		Dht22Am2302TemperatureAndHumiditySensor t = new Dht22Am2302TemperatureAndHumiditySensor(4); // 4 because for Gpio data
		for (Reading r: t.readAll()){
			System.out.println("Reading data: " + r.toString());
		}
	}
3- mvn clean install to get jar file "rpi-1.0-SNAPSHOT.jar"
4- Put this jar file to my device (raspberry pi 2) and run following command.
java -cp rpi-1.0-SNAPSHOT.jar cz.pojd.rpi.sensors.gpio.Dht22Am2302TemperatureAndHumiditySensor 

But following error is appear. 

> pi@raspberrypi ~/pi4j $ java -cp rpi-1.0-SNAPSHOT.jar cz.pojd.rpi.sensors.gpio.Dht22Am2302TemperatureAndHumiditySensor
Exception in thread "main" java.lang.NoClassDefFoundError: com/pi4j/util/NativeLibraryLoader
	at cz.pojd.rpi.sensors.gpio.Dht22Am2302TemperatureAndHumiditySensor.<clinit>(Dht22Am2302TemperatureAndHumiditySensor.java:32)
Caused by: java.lang.ClassNotFoundException: com.pi4j.util.NativeLibraryLoader
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

I dont know why because I already install pi4j so that make sure pi4j-core library is already available so that It's cannot missed the class  "com.pi4j.util.NativeLibraryLoader". Can you help me to find out what problem? Thanks you so much :(

**Comment by PoJD** [comment]
Well your command only starts using rpi jar in its classpath, so the command does not include the pi4j in classpath, hence the error. THe hawa project starts the whole webapp, take a look at pom.xml inside rpi - all those dependencies has to be provided to the running instance at runtime. I leverage support for webapps inside maven to do that for me in maven, maybe you can look into building an uberjar with all dependencies to simplify your startup of your project.
